# Generated by Django 4.2.3 on 2023-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0003_alter_count_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
