# Generated by Django 4.2.3 on 2023-07-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counting.customuser'),
        ),
    ]
