# Generated by Django 4.2.3 on 2023-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0007_remove_seasons_creation_alter_seasons_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
