# Generated by Django 4.2.3 on 2023-08-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0008_seasons_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='season_number',
            field=models.IntegerField(),
        ),
    ]
