# Generated by Django 4.2.4 on 2023-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0010_alter_seasons_season_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='creation_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
